services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: examdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  frontend:
    image: prajwalbagekari/frontend:latest
    ports:
      - "5173:5173"


  exam-service:
    image: prajwalbagekari/exam-service:latest
    depends_on:
      - postgres
    ports:
      - "8006:8006"

  gateway:
    image: prajwalbagekari/gateway:latest
    ports:
      - "8000:8000"

  pdf-service:
    image: prajwalbagekari/pdf-service:latest
    ports:
      - "8001:8001"
    volumes:
      - uploads:/app/uploads

  question-service:
    image: prajwalbagekari/question-service:latest
    ports:
      - "8002:8002"

  rag-service:
    image: prajwalbagekari/rag-service:latest
    ports:
      - "8003:8003"

  image-service:
    image: prajwalbagekari/image-service:latest
    ports:
      - "8005:8005"
    volumes:
      - uploads:/app/uploads

  langgraph-service:
    image: prajwalbagekari/langgraph-service:latest
    depends_on:
      - exam-service
      - pdf-service
      - question-service
      - rag-service
      - image-service
    ports:
      - "8008:8008"
    volumes:
      - uploads:/app/uploads

volumes:
  uploads: